// document.getElementById("parent").style.border="1px solid gray";
// document.getElementById("parent").style.height="50px";
// document.getElementById("parent").style.backgroundColor="blue"
// document.getElementById("parent").style.border="1px solid gray";
// let element=document.createElement("button")

// element.innerText="submit";
// element.style.backgroundColor="red"
// element.style.padding="10px";
// document.getElementById("parent").append(element)
// newFunction();


    // console.log(variable);
    // variable = 15;
    console.log(variable);

    let variable = 10;
function newFunction() {
    
   
    console.log(variable);
}
newFunction()
